### ISSUE TITLE
Star Players

### ISSUE THREAD

**Issue by Weemanbiggins** [blacksnotling/HDWSBBL#188] opened 2021-10-14 21:45 UTC
Star players will need to be linked to the team special rules (old world classic, favoured of... etc...) as this is the new way they are assigned, or we can add a small referance box much like the ssp totals and skill costs in "player actions"

A new box will need to be added for their special rules. Each star has one of these. Another box for a bio would be useful, can be ripped from the rulebooks of old.

Finally old stars need to be amended to match the new rules (amend the passing stat and add special rule), players not in BB20 or the applicable spikes need to be retired (they may come back).

**Comment by blacksnotling** [comment] 2021-10-19 18:50
Duplicate of https://github.com/blacksnotling/HDWSBBL/issues/186 and https://github.com/blacksnotling/HDWSBBL/issues/165

**Comment by blacksnotling** [comment] 2021-10-20 16:11
- [x]  #186
- [x] #165 
- [x] #117
- [x] #158

**Comment by blacksnotling** [comment] 2021-10-25 20:57
Closed in https://github.com/blacksnotling/HDWSBBL/commit/60af0f9aecda7803e611889ca41a3685a7010e6e

**Closed as completed by blacksnotling** 2021-10-25 20:57 UTC
Labels: Enhancement, BBLM, Admin, Front end, Component-player, Component-race, New Feature, 2020 Edition
